//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceManagement
    {
        public AttendanceManagement()
        {
            this.AttendanceManagementDetails = new HashSet<AttendanceManagementDetail>();
        }
    
        public int Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual ICollection<AttendanceManagementDetail> AttendanceManagementDetails { get; set; }
    }
}
