//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropManagement
    {
        public CropManagement()
        {
            this.FertilizerExpenses = new HashSet<FertilizerExpense>();
            this.FuelExpenses = new HashSet<FuelExpense>();
            this.Seeds = new HashSet<Seed>();
        }
    
        public int Id { get; set; }
        public int FarmId { get; set; }
        public int AreaId { get; set; }
        public string CropName { get; set; }
        public string CropDuration { get; set; }
        public System.DateTime CropStartDate { get; set; }
        public System.DateTime CropEndDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<FertilizerExpense> FertilizerExpenses { get; set; }
        public virtual ICollection<FuelExpense> FuelExpenses { get; set; }
        public virtual ICollection<Seed> Seeds { get; set; }
        public virtual Farm Farm { get; set; }
        public virtual FarmArea FarmArea { get; set; }
    }
}
