//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Positions = new HashSet<Position>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Position> Positions { get; set; }
    }
}
