//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Farm
    {
        public Farm()
        {
            this.Animals = new HashSet<Animal>();
            this.CropManagements = new HashSet<CropManagement>();
            this.FarmAreas = new HashSet<FarmArea>();
            this.Fertilizers = new HashSet<Fertilizer>();
            this.FertilizerExpenses = new HashSet<FertilizerExpense>();
            this.Fuels = new HashSet<Fuel>();
            this.FuelExpenses = new HashSet<FuelExpense>();
            this.Machineries = new HashSet<Machinery>();
            this.OtherExpenses = new HashSet<OtherExpense>();
            this.OtherItems = new HashSet<OtherItem>();
            this.Seeds = new HashSet<Seed>();
            this.SeedExpenses = new HashSet<SeedExpense>();
            this.Vehicles = new HashSet<Vehicle>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string FarmName { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string TotalArea { get; set; }
        public decimal ActualPrice { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TotalValue { get; set; }
        public decimal PaperValue { get; set; }
        public decimal Rent { get; set; }
        public string Owner { get; set; }
        public string Status { get; set; }
        public System.DateTime PurchasedDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string TotalMonths { get; set; }
    
        public virtual ICollection<Animal> Animals { get; set; }
        public virtual ICollection<CropManagement> CropManagements { get; set; }
        public virtual ICollection<FarmArea> FarmAreas { get; set; }
        public virtual ICollection<Fertilizer> Fertilizers { get; set; }
        public virtual ICollection<FertilizerExpense> FertilizerExpenses { get; set; }
        public virtual ICollection<Fuel> Fuels { get; set; }
        public virtual ICollection<FuelExpense> FuelExpenses { get; set; }
        public virtual ICollection<Machinery> Machineries { get; set; }
        public virtual ICollection<OtherExpense> OtherExpenses { get; set; }
        public virtual ICollection<OtherItem> OtherItems { get; set; }
        public virtual ICollection<Seed> Seeds { get; set; }
        public virtual ICollection<SeedExpense> SeedExpenses { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
