//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fertilizer
    {
        public Fertilizer()
        {
            this.FertilizerExpenses = new HashSet<FertilizerExpense>();
        }
    
        public int Id { get; set; }
        public int FarmId { get; set; }
        public string Brand { get; set; }
        public string FertilizerName { get; set; }
        public string Type { get; set; }
        public string Quality { get; set; }
        public string Quantity { get; set; }
        public int QuantityInNumber { get; set; }
        public int VendorId { get; set; }
        public decimal Price { get; set; }
        public decimal PricePerItem { get; set; }
        public System.DateTime DatePurchase { get; set; }
        public string PaymentBill { get; set; }
        public string OtherDescription { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual ICollection<FertilizerExpense> FertilizerExpenses { get; set; }
        public virtual VendorManagement VendorManagement { get; set; }
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
    }
}
