//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSetting
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public int RoleId { get; set; }
        public bool IsAdd { get; set; }
        public bool IsUpdate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Role Role { get; set; }
    }
}
