//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanManagement
    {
        public LoanManagement()
        {
            this.LoanReceivableFromBanks = new HashSet<LoanReceivableFromBank>();
            this.LoanReceivableFromEmployees = new HashSet<LoanReceivableFromEmployee>();
            this.ReturnLoans = new HashSet<ReturnLoan>();
            this.PaidLoans = new HashSet<PaidLoan>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public decimal LoanAmount { get; set; }
        public int NoOfInstallment { get; set; }
        public bool PerMonthOrYear { get; set; }
        public System.DateTime LoanStartDate { get; set; }
        public System.DateTime LoanEndDate { get; set; }
        public string Description { get; set; }
        public decimal IntersetRate { get; set; }
        public string Status { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> DebtSalary { get; set; }
        public string DeductedSalary { get; set; }
    
        public virtual ICollection<LoanReceivableFromBank> LoanReceivableFromBanks { get; set; }
        public virtual ICollection<LoanReceivableFromEmployee> LoanReceivableFromEmployees { get; set; }
        public virtual ICollection<ReturnLoan> ReturnLoans { get; set; }
        public virtual ICollection<PaidLoan> PaidLoans { get; set; }
        public virtual User User { get; set; }
    }
}
