//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanReceivableFromBank
    {
        public int Id { get; set; }
        public int LoanId { get; set; }
        public decimal Amount { get; set; }
        public decimal NoOfInstallment { get; set; }
        public decimal InterestRate { get; set; }
        public decimal TotalAmountTobePaid { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoanReceiveDate { get; set; }
        public System.DateTime LoanEndDate { get; set; }
        public string Description { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual LoanManagement LoanManagement { get; set; }
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
    }
}
