//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermanentEmployeeSalary
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int UserId { get; set; }
        public bool IsAllowFund { get; set; }
        public decimal BasicSalary { get; set; }
        public decimal Bonus { get; set; }
        public decimal MedicalAllowance { get; set; }
        public decimal TA_DA { get; set; }
        public decimal HouseRent { get; set; }
        public decimal UtilityAllowance { get; set; }
        public decimal ProvidentFund { get; set; }
        public Nullable<decimal> Penality { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
