//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalAccount
    {
        public PersonalAccount()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public decimal OpeningBalance { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
