//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAssignment
    {
        public int Id { get; set; }
        public string TaskName { get; set; }
        public int StaffNameId { get; set; }
        public string Description { get; set; }
        public System.DateTime DeadlineStartDate { get; set; }
        public System.DateTime DeadlineEndDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
