//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public int FarmId { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public string Type { get; set; }
        public string Power { get; set; }
        public string RegistrationNo { get; set; }
        public string Picture { get; set; }
        public string LicenseFile { get; set; }
        public string CompanyName { get; set; }
        public decimal Price { get; set; }
        public string ModelNo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int VendorId { get; set; }
        public string OtherDescription { get; set; }
        public string Condition { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int AccountId { get; set; }
        public int UserId { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual VendorManagement VendorManagement { get; set; }
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
    }
}
