//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorManagement
    {
        public VendorManagement()
        {
            this.Animals = new HashSet<Animal>();
            this.Fertilizers = new HashSet<Fertilizer>();
            this.Fuels = new HashSet<Fuel>();
            this.Machineries = new HashSet<Machinery>();
            this.Seeds = new HashSet<Seed>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string PhoneNo { get; set; }
        public string PersonalPhoneNo { get; set; }
        public string AddressInfo { get; set; }
        public decimal OpeningBalance { get; set; }
        public string OtherDescription { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<Animal> Animals { get; set; }
        public virtual ICollection<Fertilizer> Fertilizers { get; set; }
        public virtual ICollection<Fuel> Fuels { get; set; }
        public virtual ICollection<Machinery> Machineries { get; set; }
        public virtual ICollection<Seed> Seeds { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
